# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20170327_1332'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_token', models.TextField(max_length=200, null=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.IntegerField(default=1, null=True)),
                ('view_datetime', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=True)),
                ('added', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('in_cart', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qty', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fomouser',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fomouser',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='cc_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='cc_exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='credit_card',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='fomouser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='fomouser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='fomouser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Sale'),
        ),
    ]
