# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170222_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fomouser',
            name='billing_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='cc_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='cc_exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='credit_card',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='shipping_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
