# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_producthistory_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fomouser',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='fomouser',
            name='cc_code',
        ),
        migrations.RemoveField(
            model_name='fomouser',
            name='cc_exp_date',
        ),
        migrations.RemoveField(
            model_name='fomouser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='fomouser',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='fomouser',
            name='zip_code',
        ),
    ]
