# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='codename',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
