# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
