# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpicture',
            old_name='path',
            new_name='path1',
        ),
        migrations.AddField(
            model_name='productpicture',
            name='path2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='path3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='path4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='path5',
            field=models.TextField(null=True),
        ),
    ]
