# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170324_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthistory',
            old_name='user',
            new_name='fomouser',
        ),
    ]
