# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20170324_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='qty_ordered',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
