# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20170324_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='qty_ordered',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
