# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_producthistory_qty_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='fomouser',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='fomouser',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductHistory',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
