# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20170327_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uniqueproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
